# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "control-vm" do |cvm|
    # Esta será la maquina de control de Ansible
    cvm.vm.hostname = "control-vm"
    cvm.vm.network "private_network", ip: "192.168.56.2"

    # Instala todo lo relacionado con Ansible para su uso
    cvm.vm.provision "shell", path: "setup-control.sh", privileged: false
  end

  config.vm.define "host-vm" do |hvm|
    # Esta será la maquina host de Ansible
    hvm.vm.hostname = "host-vm"

    # Para poder acceder a las páginas desde el exterior, se reenvian algunos puertos
    hvm.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1" # Grafana
    hvm.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1" # Nginx
    hvm.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1" # Prometheus
    hvm.vm.network "private_network", ip: "192.168.56.3"

    # Permitir el usar otras llaves además de la provista por Vagrant
    hvm.ssh.keys_only = false

    # Configura ssh para su uso con Ansible
    hvm.vm.provision "shell", path: "setup-host.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    # Requerimientos de Nginx: 4G ram / 2 cpus
    #  Requerimientos de Grafana: 512m ram / 1 cpu
    #   Requerimientos de Ansible: 4G ram / 2 cpus
    vb.memory = 4096
    vb.cpus = 2
  end

  # Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"

  config.vm.provision "shell", path: "setup-control.sh", privileged: false
  config.vm.provision "shell", path: "setup-host.sh"

end
