- name: Configuración de Nginx
  hosts: grupoprincipal
  become: true
  tasks:
  - name: Instala Nginx en su última versión
    ansible.builtin.apt:
      update_cache: true
      name: nginx
      state: latest

  - name: Copia los archivos html
    ansible.builtin.copy:
      src: ../Nginx/html-Ansible # importante que no termine en /
      dest: /var/www/

  - name: Copia los archivos de configuración
    ansible.builtin.copy:
      src: ../Nginx/Configuración-Ansible.conf
      dest: /etc/nginx/conf.d/

  - name: Reinicia Nginx
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: nginx.service
      state: restarted
      enabled: true


- name: Configuración de Prometheus
  hosts: grupoprincipal
  become: true
  tasks:
  - name: Crea el usuario "prometheus"
    ansible.builtin.user:
      name: prometheus
      create_home: false
      system: true
      shell: /sbin/nologin
      state: present

  - name: Descarga de Prometheus
    ansible.builtin.unarchive:
      remote_src: true # No utilizar un archivo de control-vm, sino de host-vm
      src: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
      dest: /opt/
      owner: prometheus
      group: prometheus
      # Al no poseer un script de instalación en el propio archivo descargado,
      # se asume que es valido tener la instalación en el directorio /opt/, lo
      # que permitiría tener una instalación más limpia. Se recalca que es
      # igual de valido utilizar directorios como /usr/local/bin/.

  - name: Creación del directorio de datos
    ansible.builtin.file:
      path: /prometheus-data/
      state: directory
      owner: prometheus
      group: prometheus

  - name: Copia del archivo de servicio
    ansible.builtin.copy:
      src: ../Prometheus/prometheus.service
      dest: /etc/systemd/system/

  - name: Arranca Prometheus
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: prometheus.service
      state: started
      enabled: true


- name: Configuración de Grafana
  hosts: grupoprincipal
  become: true
  tasks:
  - name: Añade el repositorio de Grafana
    ansible.builtin.deb822_repository:
      name: grafana
      types: deb
      uris: https://apt.grafana.com
      signed_by: https://apt.grafana.com/gpg.key
      suites: stable
      components: main
      state: present
      enabled: true

  - name: Instala Grafana en su última versión
    ansible.builtin.apt:
      update_cache: true
      name: grafana
      state: latest

  - name: Arranca Grafana
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: grafana-server.service
      state: started
      enabled: true
